# Generated by Django 5.2.9 on 2025-12-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
