# Generated by Django 5.2.9 on 2025-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_model_book_rename_create_at_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_info',
            field=models.TextField(blank=True, null=True, verbose_name='저자 정보'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_photo',
            field=models.URLField(blank=True, null=True, verbose_name='저자 사진 URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.IntegerField(default=0, verbose_name='카테고리 ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, null=True, verbose_name='표지 이미지 URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='customer_review_rank',
            field=models.IntegerField(default=0, verbose_name='평점'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='책 소개'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='출판일'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='출판사'),
        ),
        migrations.AddField(
            model_name='book',
            name='subTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='부제'),
        ),
    ]
