# Generated by Django 5.2.4 on 2025-12-12 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('cover', models.URLField()),
                ('pub_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('subTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('author_info', models.TextField(blank=True, null=True)),
                ('author_photo', models.URLField(blank=True, null=True)),
                ('customer_review_rank', models.FloatField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
