# Generated by Django 5.2.4 on 2025-12-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voice_choice',
            field=models.CharField(default='alloy', max_length=50),
        ),
    ]
