# Generated by Django 5.2.4 on 2025-12-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='한 줄 소개'),
        ),
    ]
